import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { MyGlobalProvider } from "./stores/ContextGlobalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MyGlobalProvider>
      <html lang="en">
        <body className={inter.className}>
          <main className="flex min-h-screen flex-col">
            <Navbar />
            <div className="p-10 w-full">
              {children}
            </div>
          </main>
        </body>
      </html>
    </MyGlobalProvider>
  );
}
